"""Top-level rule template generators."""

from __future__ import annotations

import logging
from typing import Any, Dict, List

from generator.rules_creator import append_mandatory_anti_patterns
from generator.rules_sections.do_dont import _build_do_rules, _build_dont_rules
from generator.rules_sections.structure import _build_context_strategy, _build_dep_section, _build_file_structure
from generator.rules_sections.testing import _build_test_section
from generator.rules_sections.workflows import _build_workflow_section

logger = logging.getLogger(__name__)


def _generate_enhanced_rules(project_data: Dict[str, Any], config: Dict[str, Any], ctx: Dict[str, Any]) -> str:
    """Generate rules grounded in actual project analysis."""
    name = project_data["name"]
    max_desc = config.get("generation", {}).get("max_description_length", 200)
    description = project_data["description"][:max_desc]
    tech_stack = project_data["tech_stack"]
    tech_str = ", ".join(tech_stack) if tech_stack else "standard tools"

    metadata = ctx.get("metadata", {})
    project_type = metadata.get("project_type", "unknown")
    languages = metadata.get("languages", [])

    deps = ctx.get("dependencies", {})
    python_deps_raw = deps.get("python", [])
    python_deps = [d["name"] for d in python_deps_raw if d.get("constraint") != "missing"]
    missing_files = [d["name"] for d in python_deps_raw if d.get("constraint") == "missing"]
    
    node_deps = [d["name"] for d in deps.get("node", [])]

    structure = ctx.get("structure", {})
    entry_points = structure.get("entry_points", [])
    raw_patterns = structure.get("patterns", [])
    patterns = [p for p in raw_patterns if p == project_type or p.endswith("-tests")]

    test_info = ctx.get("test_patterns", {})
    test_framework = test_info.get("framework", "")
    test_files = test_info.get("test_files", 0)

    readme_data = ctx.get("readme", {})
    installation = readme_data.get("installation", "")
    usage = readme_data.get("usage", "")
    troubleshooting = readme_data.get("troubleshooting", "")
    raw_readme = readme_data.get("raw_readme", "")
    _readme_conventions: list = []
    if raw_readme:
        try:
            from generator.analyzers.readme_parser import extract_conventions

            _readme_conventions = extract_conventions(raw_readme)
        except Exception as e:  # noqa: BLE001 — optional enrichment; fallback to empty
            logger.debug(f"Expected error: {e}")

    arch_lines = []
    if project_type != "unknown":
        arch_lines.append(f"- **Project type**: {project_type}")
    if entry_points:
        arch_lines.append(f"- **Entry points**: {', '.join(entry_points)}")
    if patterns:
        arch_lines.append(f"- **Structural patterns**: {', '.join(patterns)}")
    if languages:
        arch_lines.append(f"- **Languages**: {', '.join(languages)}")
    arch_section = "\n".join(arch_lines) if arch_lines else "- Standard project layout"

    do_rules = _build_do_rules(tech_stack, python_deps, node_deps, project_type, test_framework, structure)
    if _readme_conventions:
        conv_md = "\n".join(f"- {c}" for c in _readme_conventions[:10])
        do_rules += f"\n\n**README Conventions:**\n{conv_md}"
    dont_rules = _build_dont_rules(tech_stack, python_deps, project_type, structure)

    features = project_data.get("features", [])
    priorities = features[:3] if features else []
    while len(priorities) < 3:
        defaults = ["Code quality", "Test coverage", "Documentation clarity"]
        priorities.append(defaults[len(priorities)])

    test_section = _build_test_section(test_framework, test_files, test_info, python_deps, node_deps)
    dep_section = _build_dep_section(python_deps, node_deps, missing_files)
    file_structure = _build_file_structure(structure, entry_points, patterns)
    workflow_section = _build_workflow_section(installation, usage, troubleshooting, test_framework, tech_stack)
    context_strategy = _build_context_strategy(structure, entry_points, project_type, test_info)

    template = f"""---
project: {name}
purpose: Coding & contribution rules for this workspace
version: 2.0
generated: auto
project_type: {project_type}
---

## CONTEXT

{description}

This project uses: {tech_str}

## ARCHITECTURE

{arch_section}

## FILE STRUCTURE

{file_structure}

## DEPENDENCIES

{dep_section}

## DO (must follow)

{do_rules}

## DON'T

{dont_rules}

## TESTING

{test_section}

## PRIORITIES

1. {priorities[0]}
2. {priorities[1]}
3. {priorities[2]}

## CONTEXT STRATEGY

{context_strategy}

## WORKFLOWS

{workflow_section}

---
_Generated by project-rules-generator (enhanced analysis)_
"""
    framework_hint = "react" if tech_stack and "react" in tech_stack else ""
    return append_mandatory_anti_patterns(template, framework_hint)


def _generate_basic_rules(project_data: Dict[str, Any], config: Dict[str, Any]) -> str:
    """Generate basic rules without enhanced context (fallback)."""
    name = project_data["name"]
    description = project_data["description"][: config.get("generation", {}).get("max_description_length", 200)]
    tech_stack = project_data["tech_stack"]
    features = project_data["features"]

    tech_str = ", ".join(tech_stack) if tech_stack else "standard tools"

    priorities: List[str] = []
    if features:
        priorities = features[:3]
    else:
        priorities = ["Code quality", "Documentation clarity", "Test coverage"]

    while len(priorities) < 3:
        defaults = ["Code quality", "Documentation clarity", "Test coverage", "Security", "Performance"]
        next_default = defaults[len(priorities)]
        if next_default not in priorities:
            priorities.append(next_default)

    template = f"""---
project: {name}
purpose: Coding & contribution rules for this workspace
version: 1.0
generated: auto
---

## CONTEXT

{description}{"..." if len(project_data["description"]) > len(description) else ""}

This project uses: {tech_str}

## DO (must follow)

- Use {tech_str} as the primary tech stack
- Add type hints and docstrings to all public functions
- Write tests for new features and bug fixes
- Follow existing project structure and naming conventions
- Document breaking changes in CHANGELOG.md or release notes
- Run linters/formatters before committing (black, ruff, eslint, etc.)
- Keep functions focused and under 50 lines when possible
- Review your own code before requesting review from others

## DON'T

- Don't commit secrets, API keys, or credentials to version control
- Don't use global variables without explicit justification
- Don't bypass linting rules without documenting why
- Don't modify core infrastructure without team discussion
- Don't leave commented-out code without explaining why
- Don't add dependencies without checking license compatibility

## PRIORITIES

1. {priorities[0]}
2. {priorities[1]}
3. {priorities[2]}

## WORKFLOWS

### New Feature
```bash
git checkout -b feat/descriptive-name
# Write code + tests
# Run test suite
git add .
git commit -m "feat: descriptive message"
git push origin feat/descriptive-name
# Open PR, request review, merge to main
```

### Bug Fix
```bash
git checkout -b fix/issue-description
# Fix the bug + add regression test
# Verify fix works
git add .
git commit -m "fix: resolve issue with X"
git push origin fix/issue-description
# Open PR referencing the issue
```

### Documentation
```bash
# Docs can be edited on main for small changes
git checkout main
git pull
git commit -am "docs: update README with new feature"
git push origin main
```

---
_Generated by project-rules-generator_
"""
    framework_hint = "react" if tech_stack and "react" in tech_stack else ""
    return append_mandatory_anti_patterns(template, framework_hint)
