"""Generate constitution.md — project-specific coding principles derived from analysis."""

from pathlib import Path
from typing import Any, Dict, List, Optional

from generator.prompts.skill_generation import detect_project_tools


def generate_constitution(
    project_name: str,
    enhanced_context: Dict[str, Any],
    project_path: Optional[Path] = None,
) -> str:
    """Generate constitution.md with sections derived from actual project analysis.

    Args:
        project_name: Name of the project
        enhanced_context: Full context from EnhancedProjectParser
        project_path: Optional project root for tool detection

    Returns:
        Markdown content for constitution.md
    """
    metadata = enhanced_context.get("metadata", {})
    deps = enhanced_context.get("dependencies", {})
    structure = enhanced_context.get("structure", {})
    test_info = enhanced_context.get("test_patterns", {})

    python_deps = [d["name"] for d in deps.get("python", [])]
    node_deps = [d["name"] for d in deps.get("node", [])]
    tech_stack = metadata.get("tech_stack", [])
    project_type = metadata.get("project_type", "unknown")

    code_quality = _build_code_quality_section(tech_stack, python_deps, node_deps, project_path)
    testing = _build_testing_standards_section(test_info, python_deps, tech_stack)
    architecture = _build_architecture_section(structure, project_type, python_deps, node_deps)
    dev_guidelines = _build_dev_guidelines_section(tech_stack, python_deps, project_path, structure, project_type)

    return f"""# {project_name} — Constitution

> Coding principles and standards derived from project analysis.
> This document is auto-generated and reflects the actual tools, patterns, and conventions found in the codebase.

---

## Code Quality Principles

{code_quality}

## Testing Standards

{testing}

## Architecture Decisions

{architecture}

## Development Guidelines

{dev_guidelines}

---
_Generated by project-rules-generator (constitution mode)_
"""


def _build_code_quality_section(
    tech_stack: List[str],
    python_deps: List[str],
    node_deps: List[str],
    project_path: Optional[Path],
) -> str:
    """Build code quality section from detected linters and type-hint patterns."""
    lines: List[str] = []

    # Detect linters / formatters
    tools = detect_project_tools(project_path, tech_stack)

    linters_found: List[str] = []
    if tools.get("check"):
        linters_found.append(tools["check"])
    if tools.get("lint"):
        linters_found.append(tools["lint"])
    if tools.get("format"):
        linters_found.append(tools["format"])

    if linters_found:
        lines.append("### Linting & Formatting")
        for cmd in linters_found:
            lines.append(f"- Run `{cmd}` before committing")
        lines.append("")

    # Type hints
    has_pydantic = "pydantic" in python_deps
    has_mypy = any("mypy" in t for t in linters_found) or "mypy" in python_deps
    has_typescript = "typescript" in tech_stack or "typescript" in node_deps

    type_lines: List[str] = []
    if has_mypy:
        type_lines.append("- Enforce type hints on all public APIs (`mypy` is configured)")
    elif "python" in tech_stack:
        type_lines.append("- Use type hints on all public function signatures")
    if has_pydantic:
        type_lines.append("- Use Pydantic models for data validation and serialization")
    if has_typescript:
        type_lines.append("- Use TypeScript strict mode; avoid `any` type")

    if type_lines:
        lines.append("### Type Safety")
        lines.extend(type_lines)
        lines.append("")

    # Validation patterns
    validation_lines: List[str] = []
    if has_pydantic:
        validation_lines.append("- Validate inputs with Pydantic models — not raw dicts")
    if "marshmallow" in python_deps:
        validation_lines.append("- Validate inputs with Marshmallow schemas")
    if "zod" in node_deps:
        validation_lines.append("- Validate inputs with Zod schemas")

    if validation_lines:
        lines.append("### Input Validation")
        lines.extend(validation_lines)
        lines.append("")

    if not lines:
        lines.append("- Follow standard code quality practices for the project's tech stack")

    return "\n".join(lines).rstrip()


def _build_testing_standards_section(test_info: Dict[str, Any], python_deps: List[str], tech_stack: List[str]) -> str:
    """Build testing standards from test analysis results."""
    lines: List[str] = []
    framework = test_info.get("framework", "")
    test_files = test_info.get("test_files", 0)
    has_conftest = test_info.get("has_conftest", False)
    has_fixtures = test_info.get("has_fixtures", False)
    test_patterns = test_info.get("patterns", [])

    test_cases = test_info.get("test_cases", 0)

    if framework:
        counts = f"{test_files} test files"
        if test_cases:
            counts += f", {test_cases} test cases"
        lines.append(f"- **Framework**: {framework} ({counts})")
    else:
        lines.append("- No test framework detected — adopt one before adding features")
        return "\n".join(lines)

    # Run command
    if framework == "pytest":
        lines.append("- Run `pytest` before merging any changes")
        if "pytest-cov" in python_deps:
            lines.append("- Maintain coverage: `pytest --cov`")
    elif framework == "jest":
        lines.append("- Run `npx jest` before merging any changes")

    # Fixtures
    if has_conftest:
        lines.append("- Use shared fixtures from `conftest.py` — avoid duplicating test setup")
    if has_fixtures:
        lines.append("- Store test data in `tests/fixtures/`")

    # Test patterns
    if test_patterns:
        lines.append(f"- Detected test types: {', '.join(test_patterns)}")

    # Coverage expectations
    lines.append("- Every new feature or bug fix must include corresponding tests")

    return "\n".join(lines)


def _build_architecture_section(
    structure: Dict[str, Any],
    project_type: str,
    python_deps: List[str],
    node_deps: List[str],
) -> str:
    """Build architecture decisions from structure analysis."""
    lines: List[str] = []

    if project_type != "unknown":
        lines.append(f"- **Project type**: {project_type}")

    entry_points = structure.get("entry_points", [])
    if entry_points:
        lines.append(f"- **Entry points**: {', '.join(f'`{ep}`' for ep in entry_points)}")

    # Only show primary type + test pattern, filter false-positive secondary detections
    raw_patterns = structure.get("patterns", [])
    patterns = [p for p in raw_patterns if p == project_type or p.endswith("-tests")]
    if patterns:
        lines.append(f"- **Structural patterns**: {', '.join(patterns)}")

    # Dependency injection
    if "fastapi" in python_deps:
        lines.append("- Use `Depends()` for dependency injection in route handlers")
    if "flask" in python_deps:
        lines.append("- Use Blueprints for route organization")
    if project_type == "django-app":
        lines.append("- Follow Django app conventions (models, views, urls, admin)")

    # CLI patterns
    if "click" in python_deps:
        lines.append("- Use Click decorators for CLI commands — keep command functions thin")
    if "typer" in python_deps:
        lines.append("- Use Typer for CLI commands with type-annotated parameters")

    # Async patterns
    if "fastapi" in python_deps or "uvicorn" in python_deps:
        lines.append("- Use async handlers for I/O-bound operations")
    if "asyncio" in python_deps or "aiohttp" in python_deps:
        lines.append("- Prefer async/await for concurrent operations")

    if not lines:
        lines.append("- Standard project layout — follow existing conventions")

    return "\n".join(lines)


def _build_dev_guidelines_section(
    tech_stack: List[str],
    python_deps: List[str],
    project_path: Optional[Path],
    structure: Dict[str, Any],
    project_type: str,
) -> str:
    """Build development guidelines from detected tools and conventions."""
    lines: List[str] = []

    # Tools section
    tools = detect_project_tools(project_path, tech_stack)
    if tools:
        lines.append("### Detected Tools")
        for purpose, cmd in tools.items():
            lines.append(f"- **{purpose}**: `{cmd}`")
        lines.append("")

    # Path conventions
    entry_points = structure.get("entry_points", [])
    if entry_points:
        lines.append("### Key Paths")
        for ep in entry_points:
            lines.append(f"- `{ep}`")
        lines.append("")

    # Docker
    has_docker = "docker" in tech_stack
    if project_path:
        has_docker = has_docker or (project_path / "Dockerfile").exists()
        has_docker = has_docker or (project_path / "docker-compose.yml").exists()
        has_docker = has_docker or (project_path / "docker-compose.yaml").exists()

    if has_docker:
        lines.append("### Containerization")
        lines.append("- Docker is configured for this project")
        lines.append("- Use multi-stage builds; keep final image minimal")
        lines.append("- Don't include dev dependencies in production image")
        lines.append("")

    # VCS
    lines.append("### Version Control")
    lines.append("- Never commit secrets, API keys, or `.env` files")
    lines.append("- Write descriptive commit messages following conventional commits")
    if "python" in tech_stack:
        lines.append("- Keep module imports at file top; use absolute imports within the project")

    return "\n".join(lines).rstrip()
