from pathlib import Path
from typing import Any, Dict, List

from rich.console import Console
from rich.prompt import Prompt
from rich.table import Table

console = Console()


def create_readme_interactive(project_path: Path) -> Dict[str, Any]:
    console.print("\n[bold cyan]📝 README Generator[/bold cyan]")
    console.print("Let's create a professional README!\n")
    console.print(
        "[yellow]⚠️  Enter SINGLE LINE answers (no copy-paste multi-line text)[/yellow]\n"
    )

    default_name = project_path.name

    # Clear any buffered input
    import sys

    sys.stdin.flush()

    # Step 1
    console.print("[bold]Step 1/4:[/bold] Project Name")
    project_name = Prompt.ask("  → Project name", default=default_name).strip()

    # Step 2
    console.print("\n[bold]Step 2/4:[/bold] Description")
    console.print("  [dim]One line only - describe what your project does[/dim]")
    description = Prompt.ask("  → Description", default="").strip()

    # Step 3
    console.print("\n[bold]Step 3/4:[/bold] Problem Statement")
    console.print("  [dim]One line - what problem does it solve?[/dim]")
    problem = Prompt.ask("  → Problem", default="").strip()

    # Step 4
    console.print("\n[bold]Step 4/4:[/bold] Tech Stack")
    console.print("  [dim]Comma-separated (e.g: fastapi,python,postgresql)[/dim]")
    tech_input = Prompt.ask("  → Technologies", default="python").strip()

    # Parse tech stack
    tech_stack = [t.strip() for t in tech_input.split(",") if t.strip()]

    return {
        "name": project_name,
        "description": description,
        "purpose": problem,  # Map to purpose for template compatibility
        "problem": problem,
        "tech_stack": tech_stack,
        "features": "",  # Ensure features key exists
    }


def show_generated_files(files: List[Path], skills_stats: Dict[str, int]):
    """Display success summary table."""
    console.print("\n[bold green]✅ Success! Files Generated[/bold green]\n")

    # Show files table
    table = Table(title="Generated Files", show_header=True, border_style="green")
    table.add_column("File", style="cyan", no_wrap=True)
    table.add_column("Purpose", style="white")

    for file_path in files:
        name = file_path.name
        purpose = "Unknown"
        if name == ".clinerules":
            purpose = "Main config - AI agents auto-load this"
        elif name.endswith("-rules.md"):
            purpose = "Human-readable project guidelines"
        elif name.endswith("-skills.md"):
            purpose = "Detailed skills library reference"
        elif name.endswith(".json"):
            purpose = "Skills export (JSON)"
        elif name.endswith(".yaml"):
            purpose = "Skills export (YAML)"
        elif name == "README.md":
            purpose = "Project documentation"

        table.add_row(name, purpose)

    console.print(table)

    # Skills breakdown
    console.print("\n[bold]📊 Skills Breakdown:[/bold]")

    if skills_stats.get("learned", 0) > 0:
        console.print(
            f"  🎯 [cyan]{skills_stats['learned']}[/cyan] from your previous projects "
            f"[dim](LEARNED - your patterns!)[/dim]"
        )

    if skills_stats.get("builtin", 0) > 0:
        console.print(
            f"  🔧 [blue]{skills_stats['builtin']}[/blue] universal patterns "
            f"[dim](BUILTIN - always useful)[/dim]"
        )

    if skills_stats.get("generated", 0) > 0:
        console.print(
            f"  🤖 [yellow]{skills_stats['generated']}[/yellow] newly generated by AI "
            f"[dim](saved to learned for next time!)[/dim]"
        )

    console.print("\n[bold]💡 Next steps:[/bold]")
    console.print("  1. Open your AI agent (Claude/Cursor/Windsurf)")
    console.print("  2. It will automatically load .clinerules")
    console.print("  3. Start coding with your personalized rules!\n")
