"""Generate {project}-rules.md files."""
from pathlib import Path
from typing import Dict, Any, List, Optional


def generate_rules(project_data: Dict[str, Any], config: Dict[str, Any],
                   enhanced_context: Optional[Dict[str, Any]] = None) -> str:
    """Generate {project}-rules.md content.

    When enhanced_context is provided (from EnhancedProjectParser), produces
    project-specific rules derived from actual code analysis. Otherwise falls
    back to a basic template.

    Args:
        project_data: Parsed project data from README
        config: Generation configuration
        enhanced_context: Optional full context from EnhancedProjectParser

    Returns:
        Markdown content for rules file
    """
    if enhanced_context:
        return _generate_enhanced_rules(project_data, config, enhanced_context)
    return _generate_basic_rules(project_data, config)


def _generate_enhanced_rules(project_data: Dict[str, Any], config: Dict[str, Any],
                             ctx: Dict[str, Any]) -> str:
    """Generate rules grounded in actual project analysis."""
    name = project_data['name']
    max_desc = config.get('generation', {}).get('max_description_length', 200)
    description = project_data['description'][:max_desc]
    tech_stack = project_data['tech_stack']
    tech_str = ', '.join(tech_stack) if tech_stack else 'standard tools'

    metadata = ctx.get('metadata', {})
    project_type = metadata.get('project_type', 'unknown')
    languages = metadata.get('languages', [])
    has_tests = metadata.get('has_tests', False)

    deps = ctx.get('dependencies', {})
    python_deps = [d['name'] for d in deps.get('python', [])]
    node_deps = [d['name'] for d in deps.get('node', [])]

    structure = ctx.get('structure', {})
    entry_points = structure.get('entry_points', [])
    # Only show primary type + test pattern, filter false-positive secondary detections
    raw_patterns = structure.get('patterns', [])
    patterns = [p for p in raw_patterns if p == project_type or p.endswith('-tests')]

    test_info = ctx.get('test_patterns', {})
    test_framework = test_info.get('framework', '')
    test_files = test_info.get('test_files', 0)

    readme_data = ctx.get('readme', {})
    installation = readme_data.get('installation', '')
    usage = readme_data.get('usage', '')
    troubleshooting = readme_data.get('troubleshooting', '')

    # --- Build architecture section ---
    arch_lines = []
    if project_type != 'unknown':
        arch_lines.append(f"- **Project type**: {project_type}")
    if entry_points:
        arch_lines.append(f"- **Entry points**: {', '.join(entry_points)}")
    if patterns:
        arch_lines.append(f"- **Structural patterns**: {', '.join(patterns)}")
    if languages:
        arch_lines.append(f"- **Languages**: {', '.join(languages)}")
    arch_section = '\n'.join(arch_lines) if arch_lines else '- Standard project layout'

    # --- Build DO rules from actual analysis ---
    do_rules = _build_do_rules(tech_stack, python_deps, node_deps, project_type,
                               test_framework, structure)

    # --- Build DON'T rules from actual analysis ---
    dont_rules = _build_dont_rules(tech_stack, python_deps, project_type, structure)

    # --- Build priorities from features ---
    features = project_data.get('features', [])
    priorities = features[:3] if features else []
    while len(priorities) < 3:
        defaults = ['Code quality', 'Test coverage', 'Documentation clarity']
        priorities.append(defaults[len(priorities)])

    # --- Build test section ---
    test_section = _build_test_section(test_framework, test_files, test_info)

    # --- Build dependency section ---
    dep_section = _build_dep_section(python_deps, node_deps)

    # --- Build file structure section ---
    file_structure = _build_file_structure(structure, entry_points, patterns)

    # --- Build workflow section from README ---
    workflow_section = _build_workflow_section(installation, usage, troubleshooting,
                                              test_framework, tech_stack)

    template = f"""---
project: {name}
purpose: Coding & contribution rules for this workspace
version: 2.0
generated: auto
project_type: {project_type}
---

## CONTEXT

{description}

This project uses: {tech_str}

## ARCHITECTURE

{arch_section}

## FILE STRUCTURE

{file_structure}

## DEPENDENCIES

{dep_section}

## DO (must follow)

{do_rules}

## DON'T

{dont_rules}

## TESTING

{test_section}

## PRIORITIES

1. {priorities[0]}
2. {priorities[1]}
3. {priorities[2]}

## WORKFLOWS

{workflow_section}

---
_Generated by project-rules-generator (enhanced analysis)_
"""
    return template


def _build_do_rules(tech_stack: List[str], python_deps: List[str],
                    node_deps: List[str], project_type: str,
                    test_framework: str, structure: Dict) -> str:
    """Build DO rules specific to this project's tech."""
    rules = []

    # Test framework
    if test_framework == 'pytest':
        rules.append("- Run `pytest` before committing; add tests for new features")
        if 'conftest' in str(structure):
            rules.append("- Use shared fixtures from `conftest.py` — don't duplicate test setup")
    elif test_framework == 'jest':
        rules.append("- Run `npx jest` before committing; add tests for new features")
    elif test_framework:
        rules.append(f"- Run `{test_framework}` tests before committing")
    else:
        rules.append("- Write tests for new features and bug fixes")

    # Python-specific
    if 'python' in tech_stack:
        rules.append("- Use type hints on all public function signatures")
        if 'pydantic' in python_deps:
            rules.append("- Use Pydantic models for data validation (not raw dicts)")
        if 'click' in python_deps:
            rules.append("- Use Click decorators for CLI arguments — don't parse sys.argv manually")
        if 'typer' in python_deps:
            rules.append("- Use Typer for CLI commands — keep command functions thin")

    # FastAPI-specific
    if 'fastapi' in python_deps or project_type == 'fastapi-api':
        rules.append("- Use `Depends()` for dependency injection in route handlers")
        rules.append("- Define Pydantic response models for all endpoints")

    # Django-specific
    if project_type == 'django-app':
        rules.append("- Run `python manage.py makemigrations` after model changes")
        rules.append("- Use Django ORM — don't write raw SQL without justification")

    # Flask-specific
    if 'flask' in python_deps:
        rules.append("- Use Blueprints for route organization in Flask")

    # React/TS-specific
    if 'react' in node_deps or 'react' in tech_stack:
        rules.append("- Use functional components with hooks — no class components")
        rules.append("- Keep components under 200 lines; extract sub-components when needed")
    if 'typescript' in tech_stack or 'typescript' in node_deps:
        rules.append("- Use TypeScript strict mode; avoid `any` type")

    # Docker
    if 'docker' in tech_stack:
        rules.append("- Use multi-stage Docker builds; keep final image minimal")

    # Generic structure
    rules.append("- Follow existing project structure and naming conventions")
    if any(ep.endswith('.py') for ep in structure.get('entry_points', [])):
        rules.append("- Keep module imports at file top; use absolute imports within the project")

    return '\n'.join(rules)


def _build_dont_rules(tech_stack: List[str], python_deps: List[str],
                      project_type: str, structure: Dict) -> str:
    """Build DON'T rules specific to this project."""
    rules = []

    if 'python' in tech_stack:
        rules.append("- Don't use `print()` for logging — use the `logging` module")
        rules.append("- Don't catch bare `Exception` — catch specific exceptions")
        if 'click' in python_deps:
            rules.append("- Don't use `sys.exit()` in library code — raise exceptions, let Click handle exit")

    if 'fastapi' in python_deps or project_type == 'fastapi-api':
        rules.append("- Don't use sync functions for I/O in async route handlers")
        rules.append("- Don't skip Pydantic validation by accessing `request.json()` directly")

    if 'react' in tech_stack:
        rules.append("- Don't mutate state directly — use setState/dispatch")
        rules.append("- Don't use `useEffect` without dependency arrays")

    if 'docker' in tech_stack:
        rules.append("- Don't include dev dependencies in production Docker image")

    # Always
    rules.append("- Don't commit secrets, API keys, or `.env` files")
    rules.append("- Don't add dependencies without checking license compatibility")

    return '\n'.join(rules)


def _build_test_section(test_framework: str, test_files: int,
                        test_info: Dict) -> str:
    """Build testing section from actual test analysis."""
    lines = []
    if test_framework:
        lines.append(f"- **Framework**: {test_framework}")
        lines.append(f"- **Test files**: {test_files}")
        test_patterns = test_info.get('patterns', [])
        if test_patterns:
            lines.append(f"- **Test types**: {', '.join(test_patterns)}")
        if test_info.get('has_conftest'):
            lines.append("- **Fixtures**: shared via `conftest.py`")
        if test_info.get('has_fixtures'):
            lines.append("- **Test data**: `tests/fixtures/` directory")

        # Run commands
        if test_framework == 'pytest':
            lines.append("\n```bash")
            lines.append("# Run all tests")
            lines.append("pytest")
            lines.append("# Run with coverage")
            lines.append("pytest --cov")
            lines.append("# Run specific test file")
            lines.append("pytest tests/test_specific.py -v")
            lines.append("```")
        elif test_framework == 'jest':
            lines.append("\n```bash")
            lines.append("npx jest")
            lines.append("npx jest --coverage")
            lines.append("```")
    else:
        lines.append("- No test framework detected")

    return '\n'.join(lines)


def _build_dep_section(python_deps: List[str], node_deps: List[str]) -> str:
    """Build dependency section from parsed deps."""
    lines = []
    if python_deps:
        lines.append(f"**Python** ({len(python_deps)} packages): {', '.join(python_deps[:15])}")
        if len(python_deps) > 15:
            lines.append(f"  ... and {len(python_deps) - 15} more")
    if node_deps:
        lines.append(f"**Node** ({len(node_deps)} packages): {', '.join(node_deps[:15])}")
        if len(node_deps) > 15:
            lines.append(f"  ... and {len(node_deps) - 15} more")
    if not lines:
        lines.append("No dependency files found.")
    return '\n'.join(lines)


def _build_file_structure(structure: Dict, entry_points: List[str],
                          patterns: List[str]) -> str:
    """Build file structure section."""
    lines = []
    if entry_points:
        lines.append("**Entry points:**")
        for ep in entry_points:
            lines.append(f"- `{ep}`")
    if patterns:
        lines.append("\n**Detected patterns:**")
        for p in patterns:
            lines.append(f"- {p}")
    if not lines:
        lines.append("Standard project layout.")
    return '\n'.join(lines)


def _sanitize_readme_section(text: str, max_len: int = 500) -> str:
    """Trim README section content and ensure code blocks are balanced."""
    text = text[:max_len].strip()
    # Count code fences - if odd, the last block is unclosed, so close it
    fence_count = text.count('```')
    if fence_count % 2 != 0:
        text += '\n```'
    return text


def _build_workflow_section(installation: str, usage: str,
                            troubleshooting: str, test_framework: str,
                            tech_stack: List[str]) -> str:
    """Build workflow section from README content."""
    sections = []

    if installation:
        sections.append(f"### Setup\n{_sanitize_readme_section(installation)}")

    if usage:
        sections.append(f"### Usage\n{_sanitize_readme_section(usage)}")

    if troubleshooting:
        sections.append(f"### Troubleshooting\n{_sanitize_readme_section(troubleshooting, 300)}")

    # Dev workflow
    dev_lines = ["### Development"]
    dev_lines.append("```bash")
    dev_lines.append("git checkout -b feat/descriptive-name")
    if test_framework == 'pytest':
        dev_lines.append("# Write code + tests, then run:")
        dev_lines.append("pytest")
    elif test_framework == 'jest':
        dev_lines.append("# Write code + tests, then run:")
        dev_lines.append("npx jest")
    else:
        dev_lines.append("# Write code + tests")
    dev_lines.append('git add .')
    dev_lines.append('git commit -m "feat: descriptive message"')
    dev_lines.append("```")
    sections.append('\n'.join(dev_lines))

    return '\n\n'.join(sections)


# --- Fallback for when enhanced context is unavailable ---

def _generate_basic_rules(project_data: Dict[str, Any], config: Dict[str, Any]) -> str:
    """Generate basic rules without enhanced context (fallback)."""
    name = project_data['name']
    description = project_data['description'][:config.get('generation', {}).get('max_description_length', 200)]
    tech_stack = project_data['tech_stack']
    features = project_data['features']

    tech_str = ', '.join(tech_stack) if tech_stack else 'standard tools'

    priorities = []
    if features:
        priorities = features[:3]
    else:
        priorities = ['Code quality', 'Documentation clarity', 'Test coverage']

    while len(priorities) < 3:
        defaults = ['Code quality', 'Documentation clarity', 'Test coverage', 'Security', 'Performance']
        next_default = defaults[len(priorities)]
        if next_default not in priorities:
            priorities.append(next_default)

    template = f"""---
project: {name}
purpose: Coding & contribution rules for this workspace
version: 1.0
generated: auto
---

## CONTEXT

{description}{'...' if len(project_data['description']) > len(description) else ''}

This project uses: {tech_str}

## DO (must follow)

- Use {tech_str} as the primary tech stack
- Add type hints and docstrings to all public functions
- Write tests for new features and bug fixes
- Follow existing project structure and naming conventions
- Document breaking changes in CHANGELOG.md or release notes
- Run linters/formatters before committing (black, ruff, eslint, etc.)
- Keep functions focused and under 50 lines when possible
- Review your own code before requesting review from others

## DON'T

- Don't commit secrets, API keys, or credentials to version control
- Don't use global variables without explicit justification
- Don't bypass linting rules without documenting why
- Don't modify core infrastructure without team discussion
- Don't leave commented-out code without explaining why
- Don't add dependencies without checking license compatibility

## PRIORITIES

1. {priorities[0]}
2. {priorities[1]}
3. {priorities[2]}

## WORKFLOWS

### New Feature
```bash
git checkout -b feat/descriptive-name
# Write code + tests
# Run test suite
git add .
git commit -m "feat: descriptive message"
git push origin feat/descriptive-name
# Open PR, request review, merge to main
```

### Bug Fix
```bash
git checkout -b fix/issue-description
# Fix the bug + add regression test
# Verify fix works
git add .
git commit -m "fix: resolve issue with X"
git push origin fix/issue-description
# Open PR referencing the issue
```

### Documentation
```bash
# Docs can be edited on main for small changes
git checkout main
git pull
git commit -am "docs: update README with new feature"
git push origin main
```

---
_Generated by project-rules-generator_
"""
    return template
