"""Generate {project}-rules.md files."""
from typing import Dict, Any, List


def generate_rules(project_data: Dict[str, Any], config: Dict[str, Any]) -> str:
    """Generate {project}-rules.md content.
    
    Args:
        project_data: Parsed project data from README
        config: Generation configuration
        
    Returns:
        Markdown content for rules file
    """
    name = project_data['name']
    description = project_data['description'][:config.get('generation', {}).get('max_description_length', 200)]
    tech_stack = project_data['tech_stack']
    features = project_data['features']
    
    # Build tech stack string
    tech_str = ', '.join(tech_stack) if tech_stack else 'standard tools'
    
    # Build priorities from features or defaults
    priorities = []
    if features:
        priorities = features[:3]
    else:
        priorities = ['Code quality', 'Documentation clarity', 'Test coverage']
    
    # Pad priorities to 3 if needed
    while len(priorities) < 3:
        defaults = ['Code quality', 'Documentation clarity', 'Test coverage', 'Security', 'Performance']
        next_default = defaults[len(priorities)]
        if next_default not in priorities:
            priorities.append(next_default)
    
    template = f"""---
project: {name}
purpose: Coding & contribution rules for this workspace
version: 1.0
generated: auto
---

## CONTEXT

{description}{'...' if len(project_data['description']) > len(description) else ''}

This project uses: {tech_str}

## DO (must follow)

- Use {tech_str} as the primary tech stack
- Add type hints and docstrings to all public functions
- Write tests for new features and bug fixes
- Follow existing project structure and naming conventions
- Document breaking changes in CHANGELOG.md or release notes
- Run linters/formatters before committing (black, ruff, eslint, etc.)
- Keep functions focused and under 50 lines when possible
- Review your own code before requesting review from others

## DON'T

- Don't commit secrets, API keys, or credentials to version control
- Don't use global variables without explicit justification
- Don't bypass linting rules without documenting why
- Don't modify core infrastructure without team discussion
- Don't leave commented-out code without explaining why
- Don't add dependencies without checking license compatibility

## PRIORITIES

1. {priorities[0]}
2. {priorities[1]}
3. {priorities[2]}

## WORKFLOWS

### New Feature
```bash
git checkout -b feat/descriptive-name
# Write code + tests
# Run test suite
git add .
git commit -m "feat: descriptive message"
git push origin feat/descriptive-name
# Open PR, request review, merge to main
```

### Bug Fix
```bash
git checkout -b fix/issue-description
# Fix the bug + add regression test
# Verify fix works
git add .
git commit -m "fix: resolve issue with X"
git push origin fix/issue-description
# Open PR referencing the issue
```

### Documentation
```bash
# Docs can be edited on main for small changes
git checkout main
git pull
git commit -am "docs: update README with new feature"
git push origin main
```

---
_Generated by project-rules-generator_
"""
    return template
