"""Generate project-specific skills based on detected type"""
from typing import Dict, Any, Union
from pathlib import Path
from .skill_templates import load_skill_template, TECH_SPECIFIC_SKILLS
from analyzer.project_type_detector import detect_project_type_from_data

def generate_skills(project_data: Dict[str, Any], config: Dict[str, Any], project_path: Union[str, Path] = '.') -> str:
    """Generate intelligent, project-specific skills
    
    Args:
        project_data: Parsed project data
        config: Configuration dict
        project_path: Path to project root
        
    Returns:
        Markdown content for skills file
    """
    
    # Detect project type
    type_info = detect_project_type_from_data(project_data, str(project_path))
    primary_type = type_info['primary_type']
    secondary_types = type_info['secondary_types']
    
    project_name = project_data['name']
    tech = ', '.join(project_data['tech_stack'][:3]) if project_data['tech_stack'] else 'general'
    description = project_data.get('description', '')
    
    # Start with frontmatter
    content = f"""---
project: {project_name}
purpose: Agent skills for this project
type: agent-skills
detected_type: {primary_type}
confidence: {type_info['confidence']:.2f}
---

## PROJECT CONTEXT
- **Type**: {primary_type.replace('_', ' ').title()}
- **Tech Stack**: {tech}
- **Domain**: {description[:100]}...

"""
    
    # Add core generic skills (keep 3 most useful)
    content += """## CORE SKILLS

### analyze-code
Parse and analyze codebase for quality issues.

**Tools:** read, search, exec

**Usage:**
```bash
analyze-code src/
```
Output: Quality report with suggestions

### refactor-module
Refactor following project rules.

**Input:** Module path
**Output:** Refactored code + diff

### test-coverage
Run tests and generate coverage.

**Tools:** exec pytest

**Usage:**
```bash
pytest --cov=src --cov-report=term
```
"""

    # Add TECH STACK SPECIFIC SKILLS (Dynamic)
    tech_skills_added = False
    
    # Check for direct matches in TECH_SPECIFIC_SKILLS
    for tech_item in project_data.get('tech_stack', []):
        if tech_item in TECH_SPECIFIC_SKILLS:
            if not tech_skills_added:
                content += "\n## TECH SPECIFIC SKILLS\n"
                tech_skills_added = True
            content += TECH_SPECIFIC_SKILLS[tech_item]

    # If no specific template found, but we strictly need something for the primary tech
    if not tech_skills_added and project_data.get('tech_stack'):
        primary_tech = project_data['tech_stack'][0]
        content += f"\n## {primary_tech.upper()} EXPERT\n"
        content += f"\n### {primary_tech}-expert\n"
        content += f"Expert in {primary_tech} projects, patterns, and best practices.\n\n"
        content += f"**When to use:**\n"
        content += f"- Complex {primary_tech} specific implementation\n"
        content += f"- Debugging {primary_tech} errors\n"

    # Add PRIMARY type-specific skills
    content += f"\n## {primary_type.upper().replace('_', ' ')} SKILLS\n\n"
    content += load_skill_template(primary_type)

    # Add SECONDARY type skills if confidence > 0.3
    for sec_type in secondary_types[:1]:  # Only add top secondary
        # SKIP if secondary is 'generator' - that's only for the generator itself!
        if sec_type == 'generator':
            continue
        
        content += f"\n## ADDITIONAL: {sec_type.upper().replace('_', ' ')}\n\n"
        # Add 1-2 most relevant skills from secondary template
        template = load_skill_template(sec_type)
        if template:
            # Simple heuristic to extract first skill: split by ### and take the second element (first skill)
            parts = template.split('###')
            if len(parts) > 1:
                content += '###' + parts[1]

    # Usage section
    content += f"""
## USAGE

### In IDE Agent (Claude/Gemini/Cursor/Antigravity)
Load skills from {project_name}-skills.md

### In OpenClaw
```bash
/skills load {project_name}-skills.md
```

### Manual Reference
Read this file before working on the project.

---
Generated by project-rules-generator v1.0
Detected as: {primary_type} (confidence: {type_info['confidence']:.2f})
"""

    return content
