// AUTO-GENERATED by Reflex. Do not edit. The Python source in my_app/ is
// transpiled here on every build. This file should be invisible to PRG's
// detector — but Bug8 showed it leaking into the tech_stack.

import React from "react";
import { ChatBox } from "./components/ChatBox";

export default function App(): JSX.Element {
  return <ChatBox />;
}
