import pytest
from generator.types import Skill, SkillPack
from generator.skills_generator import generate_skills

def test_generate_skills_merging():
    project_data = {
        "name": "test-project",
        "tech_stack": [],
        "description": "Test"
    }
    config = {}
    
    # Create an external pack
    external_skill = Skill(
        name="external-skill",
        description="From outside",
        category="external"
    )
    pack = SkillPack("test-pack", skills=[external_skill])
    
    # Generate
    output = generate_skills(project_data, config, format='json', external_packs=[pack])
    
    assert "external-skill" in output
    assert "From outside" in output

def test_generate_skills_deduplication():
    project_data = {
        "name": "test-project",
        "tech_stack": [], # This will generate NO specific tech skills, potentially just core
        "description": "Test"
    }
    config = {}
    
    # Assume 'analyze-code' is a core skill generated by default
    # Let's try to overwrite it with an external one
    external_skill = Skill(
        name="analyze-code",
        description="External version (should be ignored)",
        category="external"
    )
    pack = SkillPack("test-pack", skills=[external_skill])
    
    output = generate_skills(project_data, config, format='json', external_packs=[pack])
    
    # The output should NOT contain the description of the external skill
    # because core skills (added first) take precedence
    assert "External version" not in output
