"""All TechProfile entries — the full technology registry data.

Add a new technology here. All derived lookups (REGISTRY, TECH_SKILL_NAMES, …)
in lookups.py are built automatically from this list.
"""

from typing import List

from generator.tech.profile import TechProfile

_PROFILES: List[TechProfile] = [
    # -- Web frameworks -------------------------------------------------------
    TechProfile(
        name="fastapi",
        display_name="FastAPI",
        category="backend",
        skill_name="fastapi-endpoints",
        packages=["fastapi"],
        readme_keywords=["fastapi", "fast api"],
        tools=["uvicorn", "pydantic", "pytest", "httpx"],
        rules={
            "high": [
                "Use async/await for I/O operations (database, external APIs)",
                "Define Pydantic models for all request/response bodies",
                "Use Depends() for dependency injection (don't pass dependencies manually)",
                "Add response_model to all endpoints for validation",
            ],
            "medium": [
                "Use APIRouter for modular route organization",
                "Add OpenAPI tags and descriptions to endpoints",
                "Implement proper exception handlers with HTTPException",
                "Use BackgroundTasks for non-blocking operations",
            ],
            "low": [
                "Add request/response examples in docstrings",
                "Use status codes from fastapi.status module",
            ],
        },
    ),
    TechProfile(
        name="flask",
        display_name="Flask",
        category="backend",
        skill_name="flask-routes",
        packages=["flask"],
        readme_keywords=["flask"],
        tools=["flask", "pytest", "requests"],
    ),
    TechProfile(
        name="django",
        display_name="Django",
        category="backend",
        skill_name="django-views",
        packages=["django"],
        readme_keywords=["django"],
        tools=["django", "pytest", "django-admin"],
    ),
    TechProfile(
        name="express",
        display_name="Express",
        category="backend",
        skill_name="express-routes",
        packages=["express"],
        readme_keywords=["express", "expressjs"],
    ),
    # -- Frontend -------------------------------------------------------------
    TechProfile(
        name="react",
        display_name="React",
        category="frontend",
        skill_name="react-components",
        packages=["react"],
        readme_keywords=["react", "reactjs", "react.js"],
        tools=["npm", "webpack", "jest", "eslint"],
        rules={
            "high": [
                "Use functional components with hooks (not class components)",
                "Keep components pure - avoid side effects in render",
                "Use useCallback/useMemo for expensive computations",
                "Avoid prop drilling - use Context or state management",
            ],
            "medium": [
                "Split large components into smaller, reusable ones",
                "Use custom hooks to extract reusable logic",
                "Implement error boundaries for graceful failures",
                "Use React.lazy() for code splitting",
            ],
            "low": [
                "Add PropTypes or TypeScript for type safety",
                "Use React DevTools for debugging",
            ],
        },
    ),
    TechProfile(
        name="vue",
        display_name="Vue",
        category="frontend",
        skill_name="vue-components",
        packages=["vue"],
        readme_keywords=["vue", "vuejs", "vue.js"],
        tools=["npm", "vue-cli", "jest"],
    ),
    TechProfile(
        name="nextjs",
        display_name="Next.js",
        category="frontend",
        skill_name="",
        packages=["next"],
        readme_keywords=["next.js", "nextjs"],
        detection_files=["next.config.js", "next.config.ts", "next.config.mjs"],
    ),
    TechProfile(
        name="tailwindcss",
        display_name="TailwindCSS",
        category="frontend",
        skill_name="",
        packages=["tailwindcss"],
        readme_keywords=["tailwind", "tailwindcss"],
        detection_files=["tailwind.config.js", "tailwind.config.ts", "tailwind.config.mjs"],
    ),
    TechProfile(
        name="vite",
        display_name="Vite",
        category="frontend",
        skill_name="",
        packages=["vite"],
        readme_keywords=["vite"],
        detection_files=["vite.config.js", "vite.config.ts", "vite.config.mjs"],
    ),
    TechProfile(
        name="konva",
        display_name="Konva",
        category="frontend",
        skill_name="konva-nesting-canvas",
        packages=["konva"],
        readme_keywords=["konva", "konvajs", "konva.js"],
    ),
    TechProfile(
        name="canvas",
        display_name="Canvas",
        category="frontend",
        skill_name="konva-nesting-canvas",
        packages=[],
        readme_keywords=["canvas", "svg canvas", "html canvas"],
    ),
    TechProfile(
        name="threejs",
        display_name="Three.js",
        category="frontend",
        skill_name="threejs-scene",
        packages=[],
        readme_keywords=["three.js", "threejs", "three js", "webgl", "3d extrusion"],
    ),
    TechProfile(
        name="babylon",
        display_name="Babylon.js",
        category="frontend",
        skill_name="babylon-scene",
        packages=[],
        readme_keywords=["babylon", "babylonjs", "babylon.js"],
    ),
    TechProfile(
        name="chrome",
        display_name="Chrome Extension",
        category="frontend",
        skill_name="chrome-extension",
        packages=[],
        readme_keywords=["chrome", "chrome extension", "manifest.json"],
    ),
    # -- Testing --------------------------------------------------------------
    TechProfile(
        name="pytest",
        display_name="pytest",
        category="testing",
        skill_name="pytest-testing",
        packages=["pytest"],
        readme_keywords=["pytest"],
        tools=["pytest", "coverage", "pytest-cov"],
        rules={
            "high": [
                "Use fixtures for test setup/teardown (don't repeat setup)",
                "Parametrize tests with @pytest.mark.parametrize",
                "Mock external dependencies (APIs, databases)",
            ],
            "medium": [
                "Organize tests in tests/ mirroring source structure",
                "Use conftest.py for shared fixtures",
                "Add docstrings explaining what each test validates",
            ],
            "low": [
                "Use pytest.raises() for exception testing",
                "Add markers (@pytest.mark.slow) for test categories",
            ],
        },
    ),
    TechProfile(
        name="jest",
        display_name="Jest",
        category="testing",
        skill_name="jest-testing",
        packages=["jest"],
        readme_keywords=["jest"],
    ),
    # -- Infrastructure -------------------------------------------------------
    TechProfile(
        name="docker",
        display_name="Docker",
        category="infrastructure",
        skill_name="docker-deployment",
        packages=["docker"],
        readme_keywords=["docker", "dockerfile"],
        tools=["docker", "docker-compose"],
        detection_files=["Dockerfile", "Dockerfile.dev", "Dockerfile.prod"],
        rules={
            "high": [
                "Use multi-stage builds to minimize image size",
                "Don't run containers as root (use USER directive)",
                "Pin specific versions in base images (not :latest)",
            ],
            "medium": [
                "Use .dockerignore to exclude unnecessary files",
                "Set health checks with HEALTHCHECK directive",
                "Use docker-compose for multi-container setups",
            ],
        },
    ),
    TechProfile(
        name="docker-compose",
        display_name="Docker Compose",
        category="infrastructure",
        skill_name="",
        packages=[],
        readme_keywords=["docker-compose"],
        detection_files=["docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"],
    ),
    TechProfile(
        name="github-actions",
        display_name="GitHub Actions",
        category="infrastructure",
        skill_name="",
        packages=[],
        readme_keywords=["github actions"],
        detection_dirs=[".github/workflows"],
    ),
    TechProfile(
        name="kubernetes",
        display_name="Kubernetes",
        category="infrastructure",
        skill_name="",
        packages=[],
        readme_keywords=["kubernetes", "k8s"],
        tools=["kubectl", "helm"],
        detection_dirs=["k8s", "kubernetes"],
    ),
    TechProfile(
        name="uvicorn",
        display_name="Uvicorn",
        category="infrastructure",
        skill_name="uvicorn-server",
        packages=["uvicorn"],
        readme_keywords=["uvicorn"],
    ),
    TechProfile(
        name="git",
        display_name="Git",
        category="infrastructure",
        skill_name="",
        packages=[],
        readme_keywords=["git"],
        tools=["git"],
    ),
    # -- Async / messaging ----------------------------------------------------
    TechProfile(
        name="asyncio",
        display_name="asyncio",
        category="backend",
        skill_name="",
        packages=[],
        readme_keywords=["asyncio", "async"],
        rules={
            "high": [
                "Always use async/await (not callbacks or futures)",
                "Don't mix blocking and async code in same function",
                "Use asyncio.gather() for concurrent operations",
            ],
            "medium": [
                "Implement proper exception handling in async tasks",
                "Use asyncio.create_task() for fire-and-forget operations",
                "Add timeouts to async operations (asyncio.wait_for)",
            ],
        },
    ),
    TechProfile(
        name="celery",
        display_name="Celery",
        category="backend",
        skill_name="celery-tasks",
        packages=["celery"],
        readme_keywords=["celery"],
        tools=["redis-cli", "celery"],
    ),
    # -- CLI / validation / templates -----------------------------------------
    TechProfile(
        name="click",
        display_name="Click",
        category="backend",
        skill_name="click-cli",
        packages=["click"],
        readme_keywords=["click"],
        rules={
            "high": [
                "Keep @click.command() functions thin — delegate business logic to core modules",
                "Use click.testing.CliRunner for all CLI integration tests",
                "Always set exit codes explicitly: sys.exit(0) success, sys.exit(1) failure",
                "Use click.echo() for output, never print() directly in command functions",
            ],
            "medium": [
                "Group related commands with @click.group() and register in a dedicated CLI module",
                "Add --verbose / -v flag to every command for debug output",
                "Use click.Path(exists=True) for path arguments to validate early",
                "Add help strings to every @click.option() and @click.argument()",
            ],
            "low": [
                "Use click.confirm() for destructive operations",
                "Add epilog= to commands showing usage examples",
            ],
        },
    ),
    TechProfile(
        name="typer",
        display_name="Typer",
        category="backend",
        skill_name="typer-cli",
        packages=["typer"],
        readme_keywords=["typer"],
    ),
    TechProfile(
        name="pydantic",
        display_name="Pydantic",
        category="backend",
        skill_name="pydantic-validation",
        packages=["pydantic"],
        readme_keywords=["pydantic"],
        rules={
            "high": [
                "Define Pydantic models for all structured data (not raw dicts)",
                "Use Field() with description= for self-documenting models",
                "Validate at the boundary — parse input into models as early as possible",
            ],
            "medium": [
                "Use model_validator for cross-field validation logic",
                "Prefer model.model_dump() over dict() (Pydantic v2)",
                "Use Optional[X] = None for truly optional fields, not X = None",
            ],
            "low": [
                "Add json_schema_extra for OpenAPI documentation hints",
            ],
        },
    ),
    TechProfile(
        name="jinja2",
        display_name="Jinja2",
        category="backend",
        skill_name="",
        packages=["jinja2"],
        readme_keywords=["jinja2", "jinja"],
        rules={
            "high": [
                "Store all templates in templates/ with .jinja2 extension",
                "Never build markdown/HTML by string concatenation — use templates",
                "Use Environment(autoescape=False) for markdown templates (not HTML)",
            ],
            "medium": [
                "Pass only the data the template needs — avoid passing full objects",
                "Use {%- and -%} to control whitespace in generated output",
                "Test template rendering in unit tests with known fixture data",
            ],
        },
    ),
    TechProfile(
        name="rich",
        display_name="rich",
        category="backend",
        skill_name="",
        packages=["rich"],
        readme_keywords=["rich"],
    ),
    TechProfile(
        name="gitpython",
        display_name="GitPython",
        category="backend",
        skill_name="gitpython-ops",
        packages=["gitpython"],
        readme_keywords=["gitpython", "git diff", "git operations"],
        import_name="git",
    ),
    TechProfile(
        name="whisper",
        display_name="Whisper",
        category="backend",
        skill_name="",
        packages=["openai-whisper", "whisper"],
        readme_keywords=["whisper", "speech recognition"],
    ),
    TechProfile(
        name="reportlab",
        display_name="ReportLab",
        category="backend",
        skill_name="reportlab-pdf",
        packages=["reportlab"],
        readme_keywords=["reportlab"],
    ),
    TechProfile(
        name="pdf",
        display_name="PDF",
        category="backend",
        skill_name="reportlab-pdf",
        packages=[],
        readme_keywords=["pdf", "pdf generation", "pdf export"],
    ),
    TechProfile(
        name="mcp",
        display_name="MCP",
        category="backend",
        skill_name="mcp-protocol",
        packages=[],
        readme_keywords=["mcp", "model context protocol", "mcp server"],
    ),
    # -- HTTP clients ---------------------------------------------------------
    TechProfile(
        name="httpx",
        display_name="HTTPX",
        category="backend",
        skill_name="httpx-client",
        packages=["httpx"],
        readme_keywords=["httpx"],
    ),
    TechProfile(
        name="requests",
        display_name="Requests",
        category="backend",
        skill_name="requests-client",
        packages=["requests"],
        readme_keywords=["requests"],
    ),
    TechProfile(
        name="aiohttp",
        display_name="aiohttp",
        category="backend",
        skill_name="aiohttp-client",
        packages=["aiohttp"],
        readme_keywords=["aiohttp"],
    ),
    # -- Networking / protocols -----------------------------------------------
    TechProfile(
        name="websocket",
        display_name="WebSocket",
        category="backend",
        skill_name="websocket-handler",
        packages=["websockets"],
        readme_keywords=["websocket", "websockets"],
    ),
    TechProfile(
        name="graphql",
        display_name="GraphQL",
        category="backend",
        skill_name="graphql-schema",
        packages=[],
        readme_keywords=["graphql"],
    ),
    # -- Databases ------------------------------------------------------------
    TechProfile(
        name="sqlalchemy",
        display_name="SQLAlchemy",
        category="database",
        skill_name="sqlalchemy-models",
        packages=["sqlalchemy"],
        readme_keywords=["sqlalchemy"],
        tools=["alembic", "pytest"],
        rules={
            "high": [
                "Use async SQLAlchemy for async frameworks",
                "Always use sessions properly (with context manager)",
                "Define relationships with lazy='selectin' to avoid N+1",
            ],
            "medium": [
                "Use Alembic for database migrations",
                "Add indexes on frequently queried columns",
                "Implement soft deletes for critical data",
            ],
        },
    ),
    TechProfile(
        name="redis",
        display_name="Redis",
        category="database",
        skill_name="redis-caching",
        packages=["redis"],
        readme_keywords=["redis"],
        tools=["redis-cli"],
    ),
    TechProfile(
        name="mongodb",
        display_name="MongoDB",
        category="database",
        skill_name="mongodb-queries",
        packages=["pymongo", "motor"],
        readme_keywords=["mongodb", "mongo"],
    ),
    TechProfile(
        name="postgresql",
        display_name="PostgreSQL",
        category="database",
        skill_name="postgresql-queries",
        packages=["psycopg2", "psycopg2-binary", "asyncpg"],
        readme_keywords=["postgresql", "postgres"],
        tools=["psql", "pg_dump"],
    ),
    TechProfile(
        name="mysql",
        display_name="MySQL",
        category="database",
        skill_name="",
        packages=["mysql-connector-python", "pymysql", "mysqlclient"],
        readme_keywords=["mysql"],
    ),
    TechProfile(
        name="supabase",
        display_name="Supabase",
        category="database",
        skill_name="supabase-auth-storage",
        packages=["supabase"],
        readme_keywords=["supabase"],
    ),
    # -- ML / AI --------------------------------------------------------------
    TechProfile(
        name="pytorch",
        display_name="PyTorch",
        category="ml",
        skill_name="pytorch-training",
        packages=["torch"],
        readme_keywords=["pytorch", "torch"],
    ),
    TechProfile(
        name="tensorflow",
        display_name="TensorFlow",
        category="ml",
        skill_name="tensorflow-models",
        packages=["tensorflow"],
        readme_keywords=["tensorflow"],
    ),
    TechProfile(
        name="openai",
        display_name="OpenAI",
        category="ai",
        skill_name="openai-api",
        packages=["openai"],
        readme_keywords=["openai", "gpt-4", "gpt-3"],
        tools=["pytest", "ruff", "mypy"],
    ),
    TechProfile(
        name="anthropic",
        display_name="Anthropic",
        category="ai",
        skill_name="claude-cowork-workflow",
        packages=["anthropic"],
        readme_keywords=["anthropic", "claude"],
        tools=["pytest", "ruff", "mypy"],
    ),
    TechProfile(
        name="groq",
        display_name="Groq",
        category="ai",
        skill_name="groq-api",
        packages=["groq"],
        readme_keywords=["groq"],
        tools=["pytest", "ruff", "mypy"],
        rules={
            "high": [
                "Always use the GroqClient wrapper — never call the Groq API directly",
                "Set GROQ_API_KEY via environment variable, never hardcode",
                "Handle groq.RateLimitError with exponential backoff retry",
            ],
            "medium": [
                "Use llama-3.1-8b-instant for fast tasks, llama-3.3-70b for quality",
                "Log token usage per request for cost monitoring",
                "Implement provider fallback: Groq -> Gemini on failure",
            ],
        },
    ),
    TechProfile(
        name="gemini",
        display_name="Gemini",
        category="ai",
        skill_name="gemini-api",
        packages=["google-generativeai", "google-genai"],
        readme_keywords=["gemini", "google ai"],
        import_name="google",
        tools=["pytest", "ruff", "mypy"],
        rules={
            "high": [
                "Always use the GeminiClient wrapper — never call the Gemini API directly",
                "Set GEMINI_API_KEY via environment variable, never hardcode",
                "Handle google.api_core.exceptions.ResourceExhausted with retry",
            ],
            "medium": [
                "Use gemini-2.0-flash for speed, gemini-1.5-pro for complex reasoning",
                "Implement provider fallback: Gemini -> Groq on quota exhaustion",
                "Log model name and token count for every API call",
            ],
        },
    ),
    TechProfile(
        name="perplexity",
        display_name="Perplexity",
        category="ai",
        skill_name="perplexity-api",
        packages=["perplexity"],
        readme_keywords=["perplexity", "sonar"],
    ),
    TechProfile(
        name="langchain",
        display_name="LangChain",
        category="ai",
        skill_name="langchain-chains",
        packages=["langchain"],
        readme_keywords=["langchain"],
        tools=["pytest", "ruff"],
    ),
    # -- Specialised ----------------------------------------------------------
    TechProfile(
        name="dxf",
        display_name="DXF",
        category="backend",
        skill_name="dxf-processing",
        packages=["ezdxf"],
        readme_keywords=["dxf", "ezdxf", "dxf editor", "dxf upload", "dxf viewer"],
    ),
    # -- MCP / model context protocol -----------------------------------------
    # (already defined above under backend)
    # -- Languages (detection-only, no skill) ---------------------------------
    TechProfile(
        name="python",
        display_name="Python",
        category="language",
        skill_name="",
        packages=[],
        readme_keywords=["python"],
    ),
    TechProfile(
        name="typescript",
        display_name="TypeScript",
        category="language",
        skill_name="",
        packages=[],
        readme_keywords=["typescript"],
    ),
    TechProfile(
        name="javascript",
        display_name="JavaScript",
        category="language",
        skill_name="",
        packages=[],
        readme_keywords=["javascript", "node.js", "nodejs"],
    ),
    TechProfile(
        name="go",
        display_name="Go",
        category="language",
        skill_name="",
        packages=[],
        readme_keywords=["golang", "go lang"],
    ),
    TechProfile(
        name="rust",
        display_name="Rust",
        category="language",
        skill_name="",
        packages=[],
        readme_keywords=["rust", "rustlang", "cargo"],
    ),
]
