"""Project Memory Manager — bootstraps PRG memory artifacts before Ralph executes.

Responsibility:
  phase1_setup() — generate any missing memory artifacts (rules, skills, spec, tests)

Verification is intentionally separate (`prg verify` / PreflightChecker).
This class does NOT run tasks, execute code, or invoke Ralph.

Typical workflow:
    prg manager          # bootstrap memory artifacts
    prg verify           # validate project is Ralph-ready
    prg ralph "task"     # consume the memory and iterate
"""

from __future__ import annotations

import logging
import subprocess
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from generator.planning.preflight import PreflightChecker

logger = logging.getLogger(__name__)


class ProjectManager:
    """Bootstrap and validate the PRG memory layer before Ralph executes a feature.

    Memory artifacts managed:
      - README.md               (must exist; not generated — users own this)
      - .clinerules/rules.md    (generated by prg analyze)
      - .clinerules/skills/     (generated by prg analyze)
      - spec.md                 (generated via LLM if provider available, else skipped)
      - tests/                  (scaffolded if absent)
      - pytest.ini              (scaffolded if absent)
    """

    MEMORY_ARTIFACTS: List[str] = [
        "README.md",
        ".clinerules/rules.md",
        ".clinerules/skills/index.md",
        # spec.md intentionally excluded — it's optional and LLM-generated on demand
        # via `prg spec --generate`. Checking for it every run produces noise.
        "tests/",
        "pytest.ini",
    ]

    def __init__(
        self,
        project_path: Path,
        provider: Optional[str] = None,
        api_key: Optional[str] = None,
        verbose: bool = True,
    ) -> None:
        self.project_path = Path(project_path).resolve()
        self.provider = provider
        self.api_key = api_key
        self.verbose = verbose

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def run(self) -> None:
        """Bootstrap missing memory artifacts."""
        logger.info("Project Memory Manager - preparing PRG memory layer")
        self.phase1_setup()
        logger.info("Memory bootstrap complete. Run prg verify then prg ralph")

    # ------------------------------------------------------------------
    # Phase 1: Setup — generate missing memory artifacts
    # ------------------------------------------------------------------

    def phase1_setup(self) -> None:
        """Check for missing memory artifacts and generate them."""
        logger.info("\n📋 PHASE 1: Memory Artifact Setup")

        missing = self._missing_artifacts()
        if not missing:
            logger.info("   All memory artifacts present.")
            return

        logger.info("   Missing: %s", ", ".join(missing))
        self._generate_missing(missing)

        # Re-check after generation
        still_missing = self._missing_artifacts()
        if still_missing:
            logger.warning("   Could not generate: %s", ", ".join(still_missing))
        else:
            logger.info("   All memory artifacts now present.")

    def _missing_artifacts(self) -> List[str]:
        return [a for a in self.MEMORY_ARTIFACTS if not self._exists(a)]

    def _exists(self, artifact: str) -> bool:
        p = self.project_path / artifact
        return p.is_dir() if artifact.endswith("/") else p.exists()

    def _generate_missing(self, missing: List[str]) -> None:
        # rules + skills — run prg analyze
        if any(a in missing for a in [".clinerules/rules.md", ".clinerules/skills/index.md"]):
            self._generate_rules_and_skills()

        # spec.md — LLM-based if provider available, else skip with warning
        if "spec.md" in missing:
            if self.provider:
                self._generate_spec_md()
            else:
                logger.warning(
                    "   spec.md missing — pass --provider to generate it, "
                    "or create it manually with: prg spec --generate --provider <name>"
                )

        # tests/ + pytest.ini — scaffold empty structure
        if "tests/" in missing:
            (self.project_path / "tests").mkdir(exist_ok=True)
            (self.project_path / "tests" / "__init__.py").touch()
            logger.info("   Scaffolded tests/")
        if "pytest.ini" in missing:
            (self.project_path / "pytest.ini").write_text("[pytest]\ntestpaths = tests\n", encoding="utf-8")
            logger.info("   Scaffolded pytest.ini")

        # README.md — cannot be auto-generated; must exist before continuing
        if "README.md" in missing:
            logger.warning("   README.md not found — create it before running Ralph.")

    def _generate_rules_and_skills(self) -> None:
        """Run the same analysis pipeline as `prg analyze` to produce rules + skills."""
        from generator.rules_creator import CoworkRulesCreator
        from generator.skills_manager import SkillsManager
        from generator.utils.readme_bridge import find_readme

        output_dir = self.project_path / ".clinerules"
        output_dir.mkdir(parents=True, exist_ok=True)

        enhanced_context = None
        try:
            from generator.parsers.enhanced_parser import EnhancedProjectParser

            enhanced_context = EnhancedProjectParser(self.project_path).extract_full_context()
        except (
            Exception
        ) as exc:  # noqa: BLE001 — optional enrichment layer; graceful degradation if parser is missing or fails
            logger.debug("Enhanced analysis unavailable: %s", exc)

        readme_path = find_readme(self.project_path)
        readme_text = (
            readme_path.read_text(encoding="utf-8", errors="replace") if readme_path else f"# {self.project_path.name}"
        )

        creator = CoworkRulesCreator(self.project_path)
        content, metadata, _ = creator.create_rules(readme_text, enhanced_context=enhanced_context)
        creator.export_to_file(content, metadata, output_dir)
        logger.info("   Generated .clinerules/rules.md")

        skills_mgr = SkillsManager(project_path=self.project_path)
        skills_mgr.save_triggers_json(output_dir)
        skills_mgr.generate_perfect_index(project_type=metadata.project_type)
        logger.info("   Generated .clinerules/skills/index.md")

    def _generate_spec_md(self) -> None:
        """Generate a structured spec.md via LLM."""
        from generator.ai.factory import create_ai_client
        from generator.prompts.spec_generation import SPEC_GENERATION_PROMPT, SPEC_SYSTEM_MESSAGE
        from generator.utils.readme_bridge import build_project_tree

        readme_path = self.project_path / "README.md"
        context_parts: List[str] = []
        if readme_path.exists():
            context_parts.append(readme_path.read_text(encoding="utf-8", errors="replace")[:2500])

        try:
            result = subprocess.run(
                ["git", "-C", str(self.project_path), "log", "--oneline", "-20"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0 and result.stdout.strip():
                context_parts.append(f"## Recent Git Commits\n{result.stdout.strip()}")
        except (OSError, subprocess.SubprocessError):
            pass

        context_parts.append(build_project_tree(self.project_path))
        context_block = "\n\n".join(context_parts)

        client = create_ai_client(provider=self.provider or "groq", api_key=self.api_key)
        spec_content = client.generate(
            SPEC_GENERATION_PROMPT.format(context_block=context_block),
            system_message=SPEC_SYSTEM_MESSAGE,
        )
        spec_content = spec_content.encode("utf-8", errors="replace").decode("utf-8")
        (self.project_path / "spec.md").write_text(spec_content, encoding="utf-8")
        logger.info("   Generated spec.md (%d lines)", len(spec_content.splitlines()))

    # ------------------------------------------------------------------
    # Phase 2: Verify — confirm project is Ralph-ready
    # ------------------------------------------------------------------

    def phase2_verify(self) -> None:
        """Run PreflightChecker. Raises RuntimeError if critical checks fail."""
        logger.info("\n🛡️  PHASE 2: Readiness Verification")
        checker = PreflightChecker(self.project_path, task_description="prg manager readiness check")
        report = checker.run_checks()
        logger.info(report.format_report())

        if not report.all_passed:
            failed = [c.name for c in report.failed_checks]
            raise RuntimeError(
                f"Readiness verification failed: {', '.join(failed)}. "
                "Fix the issues above before running `prg ralph`."
            )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def artifact_status(self) -> dict:
        """Return a dict of artifact → exists (bool) for display."""
        return {a: self._exists(a) for a in self.MEMORY_ARTIFACTS}

    def print_status(self) -> None:
        """Print a checklist of memory artifact status."""
        logger.info("\n📄 Memory Artifact Status:")
        for artifact, exists in self.artifact_status().items():
            icon = "✅" if exists else "❌"
            logger.info("   %s %s", icon, artifact)
        ready = sum(self.artifact_status().values())
        logger.info("   %d/%d ready", ready, len(self.MEMORY_ARTIFACTS))
